name: DockerTest

on: [push, workflow_dispatch]
jobs:
  docker:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.10']
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: ${{ matrix.python-version }}
    - name: Install oedisisc
      shell: bash -l {0}
      run: |
        pip install -e .
    - name: Test script
      shell: bash
      run: |
        python -m oedisisc build --tag singlecontainerapp:0.3.0 -p python
        python -m oedisisc init -p sampleProject
        python -m oedisisc run -p sampleProject -c sampleProject/config/user_config.json --tag singlecontainerapp:0.3.0
    - name: Archive logs
      uses: actions/upload-artifact@v2
      if: always()
      with:
        name: docker_logs
        path: |
          output
